name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - name: Install dev dependencies
        run: |
          composer install --no-interaction --no-progress
      - name: Run tests
        run: |
          vendor/bin/phpunit --version
          vendor/bin/phpunit